info:
  company: Cisco Systems, Inc.
  product: Cisco-Phone-Adapter-Configuration-Utility
  softhard: '2'
matches: |
  body.icontains("cisco") && body.icontains("configuration utility")
  body.icontains("login.cgi")
