info:
  company: Jurassic
  product: Jurassic-Application-Management-System
  softhard: '2'
matches: |
  body.icontains("var _usermenusurl = '/appcenter/functions/getusermenu'")
  body.icontains("jurassic")
