info:
  company: DAS-security
  product: DAS-Security-DAS-WEB-Application-Firewall
  softhard: '1'
matches: |
  title.icontains("明御web应用防火墙")
  body.icontains("<img id=\"company_logo\" src=\"images/waf.company.png")
