info:
  company: TOPSEC
  product: Topsec-Web-application-security-&-protection-system
  softhard: '1'
matches: |
  title.icontains("web应用安全防护系统")
  body.icontains("class=\"logintop\"")
  body.icontains("href=\"login_html_files/loginstyle.css\"")
